# Create dataset with weather data

This Jupyter notebook loads weather data for all police forces and matches them with data obtained from MET Office weather stations using manually created policeForces-weatherMatching.csv file. The final result is saved in data folder as weather_dataset.csv

In [1]:
import pandas as pd

In [2]:
matching = pd.read_csv("../data/policeForces-weatherMatching.csv")

In [3]:
matching

                           policeForce     weatherStation
0       Avon and Somerset Constabulary          Yeovilton
1                  Bedfordshire Police     Cambridge Niab
2          Cambridgeshire Constabulary     Cambridge Niab
3                Cheshire Constabulary           Shawbury
4                City of London Police           Heathrow
5                     Cleveland Police             Whitby
6                 Cumbria Constabulary        Newton Rigg
7              Derbyshire Constabulary          Sheffield
8              Devon & Cornwall Police           Camborne
9                        Dorset Police               Hurn
10                 Durham Constabulary             Durham
11                        Essex Police            Manston
12        Gloucestershire Constabulary        Ross-on-wye
13           Greater Manchester Police          Sheffield
14              Hampshire Constabulary               Hurn
15          Hertfordshire Constabulary           Heathrow
16                   Humberside Police           Bradford
17                         Kent Police            Manston
18             Lancashire Constabulary           Bradford
19               Leicestershire Police   Sutton Bonington
20                 Lincolnshire Police         Waddington
21                   Merseyside Police           Shawbury
22         Metropolitan Police Service           Heathrow
23                Norfolk Constabulary     Cambridge Niab
24              North Yorkshire Police             Whitby
25             Northamptonshire Police     Cambridge Niab
26                  Northumbria Police             Durham
27              Nottinghamshire Police   Sutton Bonington
28              South Yorkshire Police          Sheffield
29                Staffordshire Police           Shawbury
30                Suffolk Constabulary     Cambridge Niab
31                       Surrey Police           Heathrow
32                       Sussex Police         Eastbourne
33                Thames Valley Police             Oxford
34                 Warwickshire Police             Oxford
35                  West Mercia Police        Ross-on-wye
36                West Midlands Police           Shawbury
37               West Yorkshire Police           Bradford
38                    Wiltshire Police          Yeovilton
39  Police Service of Northern Ireland             Armagh
40                  Dyfed-Powys Police          Aberporth
41                        Gwent Police        Ross-on-wye
42                  North Wales Police             Valley
43                  South Wales Police  Cardiff Bute Park

In [4]:
years = range(2010, 2026)
months = range(1, 13)
columns = ["tmax", "tmin", "af", "rain"]

In [5]:
import os

stations = os.listdir("../data/WeatherStations")
stations = [(x.split("."))[0] for x in stations]
stations.sort()

dict = {}

for y in years:
    for m in months:
        for c in columns:
            dict[str(y)+"_"+str(m)+"_"+c] = []

for tmp in ["2026_1_", "2026_2_", "2026_3_", "2026_4_"]:
    for c in columns:
        dict[tmp + c] = []

In [6]:
for station in stations:
    print(station)
    f = open("../data/WeatherStations/" + station + ".txt", "r")
    data = [float(x) for x in f.read().split()]
    f.close()

    ind = 2
    for y in range(2010, 2027):
        for m in range(1, 13):
            if y == 2026 and m > 4:
                break
            
            for c in columns:    
                dict[str(y)+"_"+str(m)+"_"+c].append(data[ind])
                ind += 1

            ind += 3

Aberporth
Armagh
Bradford
Camborne
Cambridge Niab
Cardiff Bute Park
Durham
Eastbourne
Heathrow
Hurn
Manston
Newton Rigg
Oxford
Ross-on-wye
Shawbury
Sheffield
Sutton Bonington
Valley
Waddington
Whitby
Yeovilton

In [7]:
df = pd.DataFrame(dict, index=stations)

In [8]:
df

,2010_1_tmax,2010_1_tmin,2010_1_af,2010_1_rain,2010_2_tmax,2010_2_tmin,2010_2_af,2010_2_rain,2010_3_tmax,2010_3_tmin,...,2026_2_af,2026_2_rain,2026_3_tmax,2026_3_tmin,2026_3_af,2026_3_rain,2026_4_tmax,2026_4_tmin,2026_4_af,2026_4_rain
Aberporth,5.1,0.9,11.0,55.4,5.9,1.4,6.0,38.1,8.5,3.0,...,0.0,85.4,11.1,6.0,0.0,54.2,14.0,6.7,0.0,27.5
Armagh,4.9,-1.0,17.0,44.0,6.2,-0.9,17.0,42.2,10.5,0.9,...,6.0,80.0,11.7,3.6,2.0,76.2,14.3,5.0,0.0,42.0
Bradford,2.9,-0.8,15.0,51.9,4.0,-0.8,17.0,55.8,9.3,2.3,...,3.0,109.0,11.5,4.1,1.0,68.6,14.9,5.1,0.0,29.0
Camborne,6.7,1.8,11.0,108.8,7.7,3.0,3.0,63.0,9.4,3.8,...,0.0,176.2,11.7,6.7,0.0,47.4,13.9,8.0,0.0,38.6
Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,10.9,2.8,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
Cardiff Bute Park,5.7,-1.1,15.0,73.5,7.3,0.8,7.0,72.1,10.8,2.8,...,2.0,176.4,13.4,5.1,0.0,49.8,16.8,6.4,0.0,38.6
Durham,3.5,-1.1,16.0,59.8,4.6,-1.0,20.0,67.6,9.7,2.0,...,4.0,63.4,12.0,3.4,2.0,44.6,14.2,4.2,2.0,21.2
Eastbourne,5.3,0.8,12.0,73.3,7.1,1.8,12.0,119.0,9.8,4.1,...,0.0,125.1,12.4,6.2,0.0,26.6,15.2,7.7,0.0,4.7
Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,11.1,3.7,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
Hurn,5.2,-2.1,20.0,60.0,7.3,0.6,9.0,76.4,10.5,2.0,...,1.0,138.0,13.0,3.7,5.0,25.6,16.5,4.9,2.0,10.0
Manston,4.0,-0.1,12.0,33.0,6.3,0.6,12.0,84.9,9.8,3.2,...,1.0,64.8,12.3,4.8,0.0,11.9,15.2,6.4,0.0,3.9
Newton Rigg,3.6,-2.8,18.0,33.1,4.8,-2.7,24.0,35.3,8.9,0.7,...,4.0,70.4,11.0,3.3,3.0,101.5,14.1,3.9,1.0,51.1
Oxford,4.7,-1.0,17.0,56.4,7.1,1.3,7.0,79.8,11.3,3.2,...,0.0,52.9,13.0,4.8,1.0,22.9,16.8,5.7,0.0,5.5
Ross-on-wye,4.7,-1.7,19.0,73.4,6.9,0.7,10.0,47.3,10.8,2.1,...,2.0,148.6,13.1,4.8,1.0,38.8,16.6,5.4,0.0,24.2
Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,10.4,1.1,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
Sheffield,3.4,0.1,14.0,48.6,4.4,0.2,11.0,53.6,9.9,3.0,...,2.0,111.0,12.0,4.8,0.0,51.6,15.3,5.6,0.0,16.6
Sutton Bonington,3.9,-0.4,16.0,37.4,5.5,0.4,11.0,41.6,10.4,2.4,...,2.0,103.2,12.3,4.4,0.0,28.8,15.9,5.0,0.0,20.4
Valley,5.9,1.0,10.0,55.0,6.9,0.7,12.0,36.4,9.3,3.2,...,1.0,76.0,11.3,5.7,1.0,51.4,14.4,6.5,0.0,29.8
Waddington,3.4,-0.7,17.0,50.2,4.7,-0.3,15.0,66.6,10.0,2.7,...,2.0,89.8,11.9,4.4,1.0,27.6,15.4,5.4,0.0,9.2
Whitby,4.3,0.4,13.0,91.2,4.7,0.5,11.0,98.5,10.0,2.7,...,1.0,87.2,12.3,4.2,0.0,36.1,14.1,4.9,1.0,7.0
Yeovilton,5.0,-2.5,18.0,49.8,7.3,1.1,9.0,64.6,10.5,1.5,...,1.0,81.8,13.1,4.3,4.0,23.6,16.4,4.9,2.0,14.2

In [9]:
df_copy = df.reset_index()

In [10]:
df_copy.rename(columns={'index': 'weatherStation'}, inplace=True)
df_copy

,weatherStation,2010_1_tmax,2010_1_tmin,2010_1_af,2010_1_rain,2010_2_tmax,2010_2_tmin,2010_2_af,2010_2_rain,2010_3_tmax,...,2026_2_af,2026_2_rain,2026_3_tmax,2026_3_tmin,2026_3_af,2026_3_rain,2026_4_tmax,2026_4_tmin,2026_4_af,2026_4_rain
0,Aberporth,5.1,0.9,11.0,55.4,5.9,1.4,6.0,38.1,8.5,...,0.0,85.4,11.1,6.0,0.0,54.2,14.0,6.7,0.0,27.5
1,Armagh,4.9,-1.0,17.0,44.0,6.2,-0.9,17.0,42.2,10.5,...,6.0,80.0,11.7,3.6,2.0,76.2,14.3,5.0,0.0,42.0
2,Bradford,2.9,-0.8,15.0,51.9,4.0,-0.8,17.0,55.8,9.3,...,3.0,109.0,11.5,4.1,1.0,68.6,14.9,5.1,0.0,29.0
3,Camborne,6.7,1.8,11.0,108.8,7.7,3.0,3.0,63.0,9.4,...,0.0,176.2,11.7,6.7,0.0,47.4,13.9,8.0,0.0,38.6
4,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,10.9,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
5,Cardiff Bute Park,5.7,-1.1,15.0,73.5,7.3,0.8,7.0,72.1,10.8,...,2.0,176.4,13.4,5.1,0.0,49.8,16.8,6.4,0.0,38.6
6,Durham,3.5,-1.1,16.0,59.8,4.6,-1.0,20.0,67.6,9.7,...,4.0,63.4,12.0,3.4,2.0,44.6,14.2,4.2,2.0,21.2
7,Eastbourne,5.3,0.8,12.0,73.3,7.1,1.8,12.0,119.0,9.8,...,0.0,125.1,12.4,6.2,0.0,26.6,15.2,7.7,0.0,4.7
8,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,11.1,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
9,Hurn,5.2,-2.1,20.0,60.0,7.3,0.6,9.0,76.4,10.5,...,1.0,138.0,13.0,3.7,5.0,25.6,16.5,4.9,2.0,10.0
10,Manston,4.0,-0.1,12.0,33.0,6.3,0.6,12.0,84.9,9.8,...,1.0,64.8,12.3,4.8,0.0,11.9,15.2,6.4,0.0,3.9
11,Newton Rigg,3.6,-2.8,18.0,33.1,4.8,-2.7,24.0,35.3,8.9,...,4.0,70.4,11.0,3.3,3.0,101.5,14.1,3.9,1.0,51.1
12,Oxford,4.7,-1.0,17.0,56.4,7.1,1.3,7.0,79.8,11.3,...,0.0,52.9,13.0,4.8,1.0,22.9,16.8,5.7,0.0,5.5
13,Ross-on-wye,4.7,-1.7,19.0,73.4,6.9,0.7,10.0,47.3,10.8,...,2.0,148.6,13.1,4.8,1.0,38.8,16.6,5.4,0.0,24.2
14,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,10.4,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
15,Sheffield,3.4,0.1,14.0,48.6,4.4,0.2,11.0,53.6,9.9,...,2.0,111.0,12.0,4.8,0.0,51.6,15.3,5.6,0.0,16.6
16,Sutton Bonington,3.9,-0.4,16.0,37.4,5.5,0.4,11.0,41.6,10.4,...,2.0,103.2,12.3,4.4,0.0,28.8,15.9,5.0,0.0,20.4
17,Valley,5.9,1.0,10.0,55.0,6.9,0.7,12.0,36.4,9.3,...,1.0,76.0,11.3,5.7,1.0,51.4,14.4,6.5,0.0,29.8
18,Waddington,3.4,-0.7,17.0,50.2,4.7,-0.3,15.0,66.6,10.0,...,2.0,89.8,11.9,4.4,1.0,27.6,15.4,5.4,0.0,9.2
19,Whitby,4.3,0.4,13.0,91.2,4.7,0.5,11.0,98.5,10.0,...,1.0,87.2,12.3,4.2,0.0,36.1,14.1,4.9,1.0,7.0
20,Yeovilton,5.0,-2.5,18.0,49.8,7.3,1.1,9.0,64.6,10.5,...,1.0,81.8,13.1,4.3,4.0,23.6,16.4,4.9,2.0,14.2

In [11]:
result = pd.merge(matching, df_copy, on="weatherStation")

In [12]:
result

,policeForce,weatherStation,2010_1_tmax,2010_1_tmin,2010_1_af,2010_1_rain,2010_2_tmax,2010_2_tmin,2010_2_af,2010_2_rain,...,2026_2_af,2026_2_rain,2026_3_tmax,2026_3_tmin,2026_3_af,2026_3_rain,2026_4_tmax,2026_4_tmin,2026_4_af,2026_4_rain
0,Avon and Somerset Constabulary,Yeovilton,5.0,-2.5,18.0,49.8,7.3,1.1,9.0,64.6,...,1.0,81.8,13.1,4.3,4.0,23.6,16.4,4.9,2.0,14.2
1,Bedfordshire Police,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
2,Cambridgeshire Constabulary,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
3,Cheshire Constabulary,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
4,City of London Police,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
5,Cleveland Police,Whitby,4.3,0.4,13.0,91.2,4.7,0.5,11.0,98.5,...,1.0,87.2,12.3,4.2,0.0,36.1,14.1,4.9,1.0,7.0
6,Cumbria Constabulary,Newton Rigg,3.6,-2.8,18.0,33.1,4.8,-2.7,24.0,35.3,...,4.0,70.4,11.0,3.3,3.0,101.5,14.1,3.9,1.0,51.1
7,Derbyshire Constabulary,Sheffield,3.4,0.1,14.0,48.6,4.4,0.2,11.0,53.6,...,2.0,111.0,12.0,4.8,0.0,51.6,15.3,5.6,0.0,16.6
8,Devon & Cornwall Police,Camborne,6.7,1.8,11.0,108.8,7.7,3.0,3.0,63.0,...,0.0,176.2,11.7,6.7,0.0,47.4,13.9,8.0,0.0,38.6
9,Dorset Police,Hurn,5.2,-2.1,20.0,60.0,7.3,0.6,9.0,76.4,...,1.0,138.0,13.0,3.7,5.0,25.6,16.5,4.9,2.0,10.0
10,Durham Constabulary,Durham,3.5,-1.1,16.0,59.8,4.6,-1.0,20.0,67.6,...,4.0,63.4,12.0,3.4,2.0,44.6,14.2,4.2,2.0,21.2
11,Essex Police,Manston,4.0,-0.1,12.0,33.0,6.3,0.6,12.0,84.9,...,1.0,64.8,12.3,4.8,0.0,11.9,15.2,6.4,0.0,3.9
12,Gloucestershire Constabulary,Ross-on-wye,4.7,-1.7,19.0,73.4,6.9,0.7,10.0,47.3,...,2.0,148.6,13.1,4.8,1.0,38.8,16.6,5.4,0.0,24.2
13,Greater Manchester Police,Sheffield,3.4,0.1,14.0,48.6,4.4,0.2,11.0,53.6,...,2.0,111.0,12.0,4.8,0.0,51.6,15.3,5.6,0.0,16.6
14,Hampshire Constabulary,Hurn,5.2,-2.1,20.0,60.0,7.3,0.6,9.0,76.4,...,1.0,138.0,13.0,3.7,5.0,25.6,16.5,4.9,2.0,10.0
15,Hertfordshire Constabulary,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
16,Humberside Police,Bradford,2.9,-0.8,15.0,51.9,4.0,-0.8,17.0,55.8,...,3.0,109.0,11.5,4.1,1.0,68.6,14.9,5.1,0.0,29.0
17,Kent Police,Manston,4.0,-0.1,12.0,33.0,6.3,0.6,12.0,84.9,...,1.0,64.8,12.3,4.8,0.0,11.9,15.2,6.4,0.0,3.9
18,Lancashire Constabulary,Bradford,2.9,-0.8,15.0,51.9,4.0,-0.8,17.0,55.8,...,3.0,109.0,11.5,4.1,1.0,68.6,14.9,5.1,0.0,29.0
19,Leicestershire Police,Sutton Bonington,3.9,-0.4,16.0,37.4,5.5,0.4,11.0,41.6,...,2.0,103.2,12.3,4.4,0.0,28.8,15.9,5.0,0.0,20.4
20,Lincolnshire Police,Waddington,3.4,-0.7,17.0,50.2,4.7,-0.3,15.0,66.6,...,2.0,89.8,11.9,4.4,1.0,27.6,15.4,5.4,0.0,9.2
21,Merseyside Police,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
22,Metropolitan Police Service,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
23,Norfolk Constabulary,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
24,North Yorkshire Police,Whitby,4.3,0.4,13.0,91.2,4.7,0.5,11.0,98.5,...,1.0,87.2,12.3,4.2,0.0,36.1,14.1,4.9,1.0,7.0
25,Northamptonshire Police,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
26,Northumbria Police,Durham,3.5,-1.1,16.0,59.8,4.6,-1.0,20.0,67.6,...,4.0,63.4,12.0,3.4,2.0,44.6,14.2,4.2,2.0,21.2
27,Nottinghamshire Police,Sutton Bonington,3.9,-0.4,16.0,37.4,5.5,0.4,11.0,41.6,...,2.0,103.2,12.3,4.4,0.0,28.8,15.9,5.0,0.0,20.4
28,South Yorkshire Police,Sheffield,3.4,0.1,14.0,48.6,4.4,0.2,11.0,53.6,...,2.0,111.0,12.0,4.8,0.0,51.6,15.3,5.6,0.0,16.6
29,Staffordshire Police,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
30,Suffolk Constabulary,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
31,Surrey Police,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
32,Sussex Police,Eastbourne,5.3,0.8,12.0,73.3,7.1,1.8,12.0,119.0,...,0.0,125.1,12.4,6.2,0.0,26.6,15.2,7.7,0.0,4.7
33,Thames Valley Police,Oxford,4.7,-1.0,17.0,56.4,7.1,1.3,7.0,79.8,...,0.0,52.9,13.0,4.8,1.0,22.9,16.8,5.7,0.0,5.5
34,Warwickshire Police,Oxford,4.7,-1.0,17.0,56.4,7.1,1.3,7.0,79.8,...,0.0,52.9,13.0,4.8,1.0,22.9,16.8,5.7,0.0,5.5
35,West Mercia Police,Ross-on-wye,4.7,-1.7,19.0,73.4,6.9,0.7,10.0,47.3,...,2.0,148.6,13.1,4.8,1.0,38.8,16.6,5.4,0.0,24.2
36,West Midlands Police,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
37,West Yorkshire Police,Bradford,2.9,-0.8,15.0,51.9,4.0,-0.8,17.0,55.8,...,3.0,109.0,11.5,4.1,1.0,68.6,14.9,5.1,0.0,29.0
38,Wiltshire Police,Yeovilton,5.0,-2.5,18.0,49.8,7.3,1.1,9.0,64.6,...,1.0,81.8,13.1,4.3,4.0,23.6,16.4,4.9,2.0,14.2
39,Police Service of Northern Ireland,Armagh,4.9,-1.0,17.0,44.0,6.2,-0.9,17.0,42.2,...,6.0,80.0,11.7,3.6,2.0,76.2,14.3,5.0,0.0,42.0
40,Dyfed-Powys Police,Aberporth,5.1,0.9,11.0,55.4,5.9,1.4,6.0,38.1,...,0.0,85.4,11.1,6.0,0.0,54.2,14.0,6.7,0.0,27.5
41,Gwent Police,Ross-on-wye,4.7,-1.7,19.0,73.4,6.9,0.7,10.0,47.3,...,2.0,148.6,13.1,4.8,1.0,38.8,16.6,5.4,0.0,24.2
42,North Wales Police,Valley,5.9,1.0,10.0,55.0,6.9,0.7,12.0,36.4,...,1.0,76.0,11.3,5.7,1.0,51.4,14.4,6.5,0.0,29.8
43,South Wales Police,Cardiff Bute Park,5.7,-1.1,15.0,73.5,7.3,0.8,7.0,72.1,...,2.0,176.4,13.4,5.1,0.0,49.8,16.8,6.4,0.0,38.6

In [13]:
result = result.set_index("policeForce")
result

,weatherStation,2010_1_tmax,2010_1_tmin,2010_1_af,2010_1_rain,2010_2_tmax,2010_2_tmin,2010_2_af,2010_2_rain,2010_3_tmax,...,2026_2_af,2026_2_rain,2026_3_tmax,2026_3_tmin,2026_3_af,2026_3_rain,2026_4_tmax,2026_4_tmin,2026_4_af,2026_4_rain
policeForce,,,,,,,,,,,,,,,,,,,,,
Avon and Somerset Constabulary,Yeovilton,5.0,-2.5,18.0,49.8,7.3,1.1,9.0,64.6,10.5,...,1.0,81.8,13.1,4.3,4.0,23.6,16.4,4.9,2.0,14.2
Bedfordshire Police,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,10.9,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
Cambridgeshire Constabulary,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,10.9,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
Cheshire Constabulary,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,10.4,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
City of London Police,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,11.1,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
Cleveland Police,Whitby,4.3,0.4,13.0,91.2,4.7,0.5,11.0,98.5,10.0,...,1.0,87.2,12.3,4.2,0.0,36.1,14.1,4.9,1.0,7.0
Cumbria Constabulary,Newton Rigg,3.6,-2.8,18.0,33.1,4.8,-2.7,24.0,35.3,8.9,...,4.0,70.4,11.0,3.3,3.0,101.5,14.1,3.9,1.0,51.1
Derbyshire Constabulary,Sheffield,3.4,0.1,14.0,48.6,4.4,0.2,11.0,53.6,9.9,...,2.0,111.0,12.0,4.8,0.0,51.6,15.3,5.6,0.0,16.6
Devon & Cornwall Police,Camborne,6.7,1.8,11.0,108.8,7.7,3.0,3.0,63.0,9.4,...,0.0,176.2,11.7,6.7,0.0,47.4,13.9,8.0,0.0,38.6
Dorset Police,Hurn,5.2,-2.1,20.0,60.0,7.3,0.6,9.0,76.4,10.5,...,1.0,138.0,13.0,3.7,5.0,25.6,16.5,4.9,2.0,10.0
Durham Constabulary,Durham,3.5,-1.1,16.0,59.8,4.6,-1.0,20.0,67.6,9.7,...,4.0,63.4,12.0,3.4,2.0,44.6,14.2,4.2,2.0,21.2
Essex Police,Manston,4.0,-0.1,12.0,33.0,6.3,0.6,12.0,84.9,9.8,...,1.0,64.8,12.3,4.8,0.0,11.9,15.2,6.4,0.0,3.9
Gloucestershire Constabulary,Ross-on-wye,4.7,-1.7,19.0,73.4,6.9,0.7,10.0,47.3,10.8,...,2.0,148.6,13.1,4.8,1.0,38.8,16.6,5.4,0.0,24.2
Greater Manchester Police,Sheffield,3.4,0.1,14.0,48.6,4.4,0.2,11.0,53.6,9.9,...,2.0,111.0,12.0,4.8,0.0,51.6,15.3,5.6,0.0,16.6
Hampshire Constabulary,Hurn,5.2,-2.1,20.0,60.0,7.3,0.6,9.0,76.4,10.5,...,1.0,138.0,13.0,3.7,5.0,25.6,16.5,4.9,2.0,10.0
Hertfordshire Constabulary,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,11.1,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
Humberside Police,Bradford,2.9,-0.8,15.0,51.9,4.0,-0.8,17.0,55.8,9.3,...,3.0,109.0,11.5,4.1,1.0,68.6,14.9,5.1,0.0,29.0
Kent Police,Manston,4.0,-0.1,12.0,33.0,6.3,0.6,12.0,84.9,9.8,...,1.0,64.8,12.3,4.8,0.0,11.9,15.2,6.4,0.0,3.9
Lancashire Constabulary,Bradford,2.9,-0.8,15.0,51.9,4.0,-0.8,17.0,55.8,9.3,...,3.0,109.0,11.5,4.1,1.0,68.6,14.9,5.1,0.0,29.0
Leicestershire Police,Sutton Bonington,3.9,-0.4,16.0,37.4,5.5,0.4,11.0,41.6,10.4,...,2.0,103.2,12.3,4.4,0.0,28.8,15.9,5.0,0.0,20.4
Lincolnshire Police,Waddington,3.4,-0.7,17.0,50.2,4.7,-0.3,15.0,66.6,10.0,...,2.0,89.8,11.9,4.4,1.0,27.6,15.4,5.4,0.0,9.2
Merseyside Police,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,10.4,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
Metropolitan Police Service,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,11.1,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
Norfolk Constabulary,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,10.9,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
North Yorkshire Police,Whitby,4.3,0.4,13.0,91.2,4.7,0.5,11.0,98.5,10.0,...,1.0,87.2,12.3,4.2,0.0,36.1,14.1,4.9,1.0,7.0
Northamptonshire Police,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,10.9,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
Northumbria Police,Durham,3.5,-1.1,16.0,59.8,4.6,-1.0,20.0,67.6,9.7,...,4.0,63.4,12.0,3.4,2.0,44.6,14.2,4.2,2.0,21.2
Nottinghamshire Police,Sutton Bonington,3.9,-0.4,16.0,37.4,5.5,0.4,11.0,41.6,10.4,...,2.0,103.2,12.3,4.4,0.0,28.8,15.9,5.0,0.0,20.4
South Yorkshire Police,Sheffield,3.4,0.1,14.0,48.6,4.4,0.2,11.0,53.6,9.9,...,2.0,111.0,12.0,4.8,0.0,51.6,15.3,5.6,0.0,16.6
Staffordshire Police,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,10.4,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
Suffolk Constabulary,Cambridge Niab,3.9,-0.4,15.0,46.6,6.1,0.4,12.0,70.6,10.9,...,2.0,58.0,12.8,4.1,3.0,18.4,17.3,5.0,1.0,1.6
Surrey Police,Heathrow,4.5,-0.3,15.0,51.8,6.9,1.7,8.0,100.4,11.1,...,0.0,85.6,13.5,5.1,0.0,27.4,17.8,6.8,0.0,4.8
Sussex Police,Eastbourne,5.3,0.8,12.0,73.3,7.1,1.8,12.0,119.0,9.8,...,0.0,125.1,12.4,6.2,0.0,26.6,15.2,7.7,0.0,4.7
Thames Valley Police,Oxford,4.7,-1.0,17.0,56.4,7.1,1.3,7.0,79.8,11.3,...,0.0,52.9,13.0,4.8,1.0,22.9,16.8,5.7,0.0,5.5
Warwickshire Police,Oxford,4.7,-1.0,17.0,56.4,7.1,1.3,7.0,79.8,11.3,...,0.0,52.9,13.0,4.8,1.0,22.9,16.8,5.7,0.0,5.5
West Mercia Police,Ross-on-wye,4.7,-1.7,19.0,73.4,6.9,0.7,10.0,47.3,10.8,...,2.0,148.6,13.1,4.8,1.0,38.8,16.6,5.4,0.0,24.2
West Midlands Police,Shawbury,4.0,-1.9,20.0,57.4,5.9,-0.9,18.0,25.8,10.4,...,3.0,98.8,12.4,3.7,3.0,32.2,15.5,3.8,3.0,17.0
West Yorkshire Police,Bradford,2.9,-0.8,15.0,51.9,4.0,-0.8,17.0,55.8,9.3,...,3.0,109.0,11.5,4.1,1.0,68.6,14.9,5.1,0.0,29.0
Wiltshire Police,Yeovilton,5.0,-2.5,18.0,49.8,7.3,1.1,9.0,64.6,10.5,...,1.0,81.8,13.1,4.3,4.0,23.6,16.4,4.9,2.0,14.2
Police Service of Northern Ireland,Armagh,4.9,-1.0,17.0,44.0,6.2,-0.9,17.0,42.2,10.5,...,6.0,80.0,11.7,3.6,2.0,76.2,14.3,5.0,0.0,42.0
Dyfed-Powys Police,Aberporth,5.1,0.9,11.0,55.4,5.9,1.4,6.0,38.1,8.5,...,0.0,85.4,11.1,6.0,0.0,54.2,14.0,6.7,0.0,27.5
Gwent Police,Ross-on-wye,4.7,-1.7,19.0,73.4,6.9,0.7,10.0,47.3,10.8,...,2.0,148.6,13.1,4.8,1.0,38.8,16.6,5.4,0.0,24.2
North Wales Police,Valley,5.9,1.0,10.0,55.0,6.9,0.7,12.0,36.4,9.3,...,1.0,76.0,11.3,5.7,1.0,51.4,14.4,6.5,0.0,29.8
South Wales Police,Cardiff Bute Park,5.7,-1.1,15.0,73.5,7.3,0.8,7.0,72.1,10.8,...,2.0,176.4,13.4,5.1,0.0,49.8,16.8,6.4,0.0,38.6

In [14]:
result.to_csv("../data/weather_dataset.csv", index=True)